name: EasyBMSignMarkers
version: ${version}
main: dev.deimoslabs.easysignmarkers.SignMarkers
api-version: 1.19
folia-supported: true
authors: [deimiczny]
depend: [BlueMap]
description: Easily add markers to BlueMap with in-game signs